config/routes.rb
Rails.application.routes.draw do
  resources :sensor_data do
    collection do
      post :import
    end
  end
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home/index'
  root 'home#index'


  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  post '/users' => 'users#create'

  get 'login', to: 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/sensor_data_helper.rb
module SensorDataHelper
end

app/views/sensor_data/edit.html.erb
<h1>Editing Sensor Datum</h1>

<%= render 'form', sensor_datum: @sensor_datum %>

<%= link_to 'Show', @sensor_datum %> |
<%= link_to 'Back', sensor_data_path %>

app/views/sensor_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sensor Data</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Snr 1</th>
      <th>Snr 2</th>
      <th>Snr 3</th>
      <th>Snr 4</th>
      <th>Snr 5</th>
      <th>Snr 6</th>
      <th>Snr 7</th>
      <th>Snr 8</th>
      <th>Snr 9</th>
      <th>Snr 10</th>
      <th>Snr 11</th>
      <th>Snr 12</th>
      <th>Snr 13</th>
      <th>Snr 14</th>
      <th>Snr 15</th>
      <th>Snr 16</th>
      <th>Snr 17</th>
      <th>Snr 18</th>
      <th>Snr 19</th>
      <th>Snr 20</th>
      <th>Snr 21</th>
      <th>Snr 22</th>
      <th>Snr 23</th>
      <th>Snr 24</th>
      <th>Snr 25</th>
      <th>Snr 26</th>
      <th>Snr 27</th>
      <th>Snr 28</th>
      <th>Snr 29</th>
      <th>Snr 30</th>
      <th>Snr 31</th>
      <th>Snr 32</th>
      <th>Snr 33</th>
      <th>Snr 34</th>
      <th>Snr 35</th>
      <th>Snr 36</th>
      <th>Snr 37</th>
      <th>Snr 38</th>
      <th>Snr 39</th>
      <th>Snr 40</th>
      <th>Snr 41</th>
      <th>Snr 42</th>
      <th>Snr 43</th>
      <th>Snr 44</th>
      <th>Snr 45</th>
      <th>Snr 46</th>
      <th>Snr 47</th>
      <th>Snr 48</th>
      <th>Snr 49</th>
      <th>Snr 50</th>
      <th>Snr 51</th>
      <th>Snr 52</th>
      <th>Snr 53</th>
      <th>Snr 54</th>
      <th>Snr 55</th>
      <th>Snr 56</th>
      <th>Snr 57</th>
      <th>Snr 58</th>
      <th>Snr 59</th>
      <th>Snr 60</th>
      <th>Snr 61</th>
      <th>Snr 62</th>
      <th>Snr 63</th>
      <th>Snr 64</th>
      <th>Snr 65</th>
      <th>Snr 66</th>
      <th>Snr 67</th>
      <th>Snr 68</th>
      <th>Snr 69</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @sensor_data.each do |sensor_datum| %>
      <tr>
        <td><%= sensor_datum.id %></td>
        <td><%= sensor_datum.sensor_1 %></td>
        <td><%= sensor_datum.sensor_2 %></td>
        <td><%= sensor_datum.sensor_3 %></td>
        <td><%= sensor_datum.sensor_4 %></td>
        <td><%= sensor_datum.sensor_5 %></td>
        <td><%= sensor_datum.sensor_6 %></td>
        <td><%= sensor_datum.sensor_7 %></td>
        <td><%= sensor_datum.sensor_8 %></td>
        <td><%= sensor_datum.sensor_9 %></td>
        <td><%= sensor_datum.sensor_10 %></td>
        <td><%= sensor_datum.sensor_11 %></td>
        <td><%= sensor_datum.sensor_12 %></td>
        <td><%= sensor_datum.sensor_13 %></td>
        <td><%= sensor_datum.sensor_14 %></td>
        <td><%= sensor_datum.sensor_15 %></td>
        <td><%= sensor_datum.sensor_16 %></td>
        <td><%= sensor_datum.sensor_17 %></td>
        <td><%= sensor_datum.sensor_18 %></td>
        <td><%= sensor_datum.sensor_19 %></td>
        <td><%= sensor_datum.sensor_20 %></td>
        <td><%= sensor_datum.sensor_21 %></td>
        <td><%= sensor_datum.sensor_22 %></td>
        <td><%= sensor_datum.sensor_23 %></td>
        <td><%= sensor_datum.sensor_24 %></td>
        <td><%= sensor_datum.sensor_25 %></td>
        <td><%= sensor_datum.sensor_26 %></td>
        <td><%= sensor_datum.sensor_27 %></td>
        <td><%= sensor_datum.sensor_28 %></td>
        <td><%= sensor_datum.sensor_29 %></td>
        <td><%= sensor_datum.sensor_30 %></td>
        <td><%= sensor_datum.sensor_31 %></td>
        <td><%= sensor_datum.sensor_32 %></td>
        <td><%= sensor_datum.sensor_33 %></td>
        <td><%= sensor_datum.sensor_34 %></td>
        <td><%= sensor_datum.sensor_35 %></td>
        <td><%= sensor_datum.sensor_36 %></td>
        <td><%= sensor_datum.sensor_37 %></td>
        <td><%= sensor_datum.sensor_38 %></td>
        <td><%= sensor_datum.sensor_39 %></td>
        <td><%= sensor_datum.sensor_40 %></td>
        <td><%= sensor_datum.sensor_41 %></td>
        <td><%= sensor_datum.sensor_42 %></td>
        <td><%= sensor_datum.sensor_43 %></td>
        <td><%= sensor_datum.sensor_44 %></td>
        <td><%= sensor_datum.sensor_45 %></td>
        <td><%= sensor_datum.sensor_46 %></td>
        <td><%= sensor_datum.sensor_47 %></td>
        <td><%= sensor_datum.sensor_48 %></td>
        <td><%= sensor_datum.sensor_49 %></td>
        <td><%= sensor_datum.sensor_50 %></td>
        <td><%= sensor_datum.sensor_51 %></td>
        <td><%= sensor_datum.sensor_52 %></td>
        <td><%= sensor_datum.sensor_53 %></td>
        <td><%= sensor_datum.sensor_54 %></td>
        <td><%= sensor_datum.sensor_55 %></td>
        <td><%= sensor_datum.sensor_56 %></td>
        <td><%= sensor_datum.sensor_57 %></td>
        <td><%= sensor_datum.sensor_58 %></td>
        <td><%= sensor_datum.sensor_59 %></td>
        <td><%= sensor_datum.sensor_60 %></td>
        <td><%= sensor_datum.sensor_61 %></td>
        <td><%= sensor_datum.sensor_62 %></td>
        <td><%= sensor_datum.sensor_63 %></td>
        <td><%= sensor_datum.sensor_64 %></td>
        <td><%= sensor_datum.sensor_65 %></td>
        <td><%= sensor_datum.sensor_66 %></td>
        <td><%= sensor_datum.sensor_67 %></td>
        <td><%= sensor_datum.sensor_68 %></td>
        <td><%= sensor_datum.sensor_69 %></td>
        <!-- <td><%= link_to 'Show', sensor_datum %></td>
        <td><%= link_to 'Edit', edit_sensor_datum_path(sensor_datum) %></td>
        <td><%= link_to 'Destroy', sensor_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
<div class="cli_alert" role="alert" style="display:none;" id="alerMsg"></div>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h4>Import datos</h4>
        </div>
        <div class="card-body">
          <%= form_tag import_sensor_data_path, id: "form_file_csv" , multipart: true do %>
            <%= file_field_tag :file, :accept => ".csv", class: "btn btn-primary" %>
            <%= submit_tag "import csv", id: "btn_sumit_file", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

<br>
<br>

app/views/sensor_data/new.html.erb
<h1>New Sensor Datum</h1>

<%= render 'form', sensor_datum: @sensor_datum %>

<%= link_to 'Back', sensor_data_path %>