config/routes.rb
Rails.application.routes.draw do
  resources :sensor_data do
    collection do
      post :import
    end
  end
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home/index'
  root 'home#index'


  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  post '/users' => 'users#create'

  get 'login', to: 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GraphicData</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" /> -->
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous"> -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <style media="screen">
      .bootstrap-datetimepicker-widget table td span {
            display: inline-block;
            width: 40px !important;
            height: 40px;
            line-height: 40px;
            margin: 2px 1.5px;
            cursor: pointer;
            border-radius: 0.25rem;
        }
        a:hover {
          background-color: #00000000 !important;
        }
        .dropdown:hover>.dropdown-menu {
          display: block;
        }

        .dropdown>.dropdown-toggle:active {
          /*Without this, clicking will make it sticky*/
            pointer-events: none;
        }

        .dropdown-submenu:hover > .dropdown-menu {
            display: block;
        }


    </style>

    <% if current_user %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <a class="navbar-brand" href="#"> <%= current_user.user_name %>.</a>
          <ul class="navbar-nav mr-auto">

            <% if current_user.type_user.to_i == 1 %>
              <li class="nav-item dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Menu
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <%= link_to "Dashboard", home_index_path, class:'dropdown-item' %>
                  <%= link_to "Datos de sensor", sensor_data_path, class:'dropdown-item' %>
                  <%= link_to "Usuarios", users_path, class:'dropdown-item' %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Cerrar secion", logout_path, class:'dropdown-item' %>
                </div>
              </li>
            <%else%>
              <li class="nav-item active">
                <%= link_to "Cerrar secion", logout_path, class:'nav-link' %>
              <li>
            <%end%>

          </ul>

        </div>

      </nav>
    <% end %>

    <div class="col-md-12">
      <%= yield %>
    </div>
  </body>
  <script>
      $(document).ready(function() {
         function disablePrev() { window.history.forward() }
         window.onload = disablePrev();
         window.onpageshow = function(evt) { if (evt.persisted) disableBack() }

         $(".dropdown-toggle").on("mouseenter", function () {
              // make sure it is not shown:
              if (!$(this).parent().hasClass("show")) {
                  $(this).click();
              }
          });

        	$('#btn_sumit_file').click(function(e){
        		 e.preventDefault();
        	    if ($('#file').get(0).files.length === 0) {
        			$('#alerMsg').addClass("alert alert-danger");
        			$('#alerMsg').attr("style", "display:block");
        			$('#alerMsg').html("Aun no ha seleccionado algún archivo valido");
        		}else{
        			$('#modal_loading').modal('toggle');
        			$("#form_file_csv").submit();
        		}
        	});

      });
   </script>
</html>